# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/imagenet --type imagenet --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/imagenet --type imagenet --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/imagenet --type imagenet --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/imagenet --type imagenet --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/imagenet --type imagenet --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/pets --type pets --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/pets --type pets --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/pets --type pets --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/pets --type pets --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/pets --type pets --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/CUB --type cub --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/CUB --type cub --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/CUB --type cub --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CUB --type cub --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CUB --type cub --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/food101 --type foods --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/food101 --type foods --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/food101 --type foods --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/food101 --type foods --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/food101 --type foods --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a RN50 --data_path /path/to/place365 --type place --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/32 --data_path /path/to/place365 --type place --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-B/16 --data_path /path/to/place365 --type place --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/place365 --type place --k 50

# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 5
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 10
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 15
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 20
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 25
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 30
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 35
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 40
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 45
# CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/place365 --type place --k 50


CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MontgomerySet --type Lung --k 50

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MontgomerySet --type Lung --k 50

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/ChinaSet --type Lung --k 50

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/ChinaSet --type Lung --k 50

# # # CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/chest_xray --type Lung --k 10
# # # CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/chest_xray  --type Lung --k 10

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/IDRiD --type eyes --k 50

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/IDRiD --type eyes --k 50

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/CataractDataset --type cataract --k 50

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/CataractDataset --type cataract --k 50

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14 --data_path /path/to/MalariaDataset --type Cell --k 50

CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 5
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 10
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 15
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 20
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 25
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 30
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 35
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 40
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 45
CUDA_VISIBLE_DEVICES=1 python Main.py -a ViT-L/14@336px --data_path /path/to/MalariaDataset --type Cell --k 50